#!/usr/bin/env bash
set -Eeuo pipefail

CONTAINER="${1:-crafty-controller}"
UUID="${2:-}"
PORT="${3:-8110}"
PUBLIC_URL="${4:-}"

[[ -n "$UUID" ]] || {
  echo "Usage: $0 CONTAINER UUID [PUERTO] [URL_PUBLICA]" >&2
  exit 2
}
[[ "$PORT" =~ ^[0-9]+$ ]] && (( PORT >= 1 && PORT <= 65535 )) || {
  echo "[ERROR] Invalid port: $PORT" >&2
  exit 2
}

docker inspect "$CONTAINER" >/dev/null 2>&1 || {
  echo "[ERROR] Missing container: $CONTAINER" >&2
  exit 1
}

ROOT="/crafty/servers/$UUID"

CONFIG="$(
  docker exec "$CONTAINER" sh -lc "
    set -eu
    for f in \
      '$ROOT/squaremap/config.yml' \
      '$ROOT/plugins/squaremap/config.yml' \
      '$ROOT/plugins/Squaremap/config.yml' \
      '$ROOT/config/squaremap/config.yml'
    do
      if [ -f \"\$f\" ]; then
        printf '%s\n' \"\$f\"
        exit 0
      fi
    done

    find '$ROOT' -maxdepth 6 -type f -path '*/squaremap/config.yml' -print -quit
  " | tr -d '\r'
)"

if [[ -z "$CONFIG" ]]; then
  echo "[ERROR] squaremap config.yml was not found." >&2
  echo "Rutas revisadas:" >&2
  echo "  $ROOT/squaremap/config.yml" >&2
  echo "  $ROOT/plugins/squaremap/config.yml" >&2
  echo "  $ROOT/config/squaremap/config.yml" >&2
  echo >&2
  echo "Diagnostics:" >&2
  docker exec "$CONTAINER" find "$ROOT" -maxdepth 6 -type f \
    \( -iname 'config.yml' -o -iname '*squaremap*' \) -print 2>/dev/null | head -n 100 >&2 || true
  exit 1
fi

STAMP="$(date +%Y%m%d-%H%M%S)"
docker exec "$CONTAINER" cp -p "$CONFIG" "$CONFIG.pre-player-panel-$STAMP"

docker exec -i "$CONTAINER" python3 - "$CONFIG" "$PORT" "$PUBLIC_URL" <<'PY'
from __future__ import annotations

import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
port = int(sys.argv[2])
public_url = sys.argv[3].strip()
lines = path.read_text(encoding="utf-8").splitlines()

def indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" "))

def find_block(block_path: list[str]) -> tuple[int, int, int] | None:
    start = 0
    end = len(lines)
    parent_indent = -1

    for key in block_path:
        pattern = re.compile(r"^(\s*)" + re.escape(key) + r":\s*(?:#.*)?$")
        found = None

        for index in range(start, end):
            match = pattern.match(lines[index])
            if match and len(match.group(1)) > parent_indent:
                found = (index, len(match.group(1)))
                break

        if found is None:
            return None

        block_line, parent_indent = found
        start = block_line + 1
        end = len(lines)

        for index in range(start, len(lines)):
            stripped = lines[index].strip()
            if stripped and not stripped.startswith("#") and indent_of(lines[index]) <= parent_indent:
                end = index
                break

    return start, end, parent_indent

def set_existing(path_parts: list[str], value: str, required: bool = True) -> bool:
    parent = find_block(path_parts[:-1])
    if parent is None:
        if required:
            raise SystemExit("Block not found: " + ".".join(path_parts[:-1]))
        return False

    start, end, parent_indent = parent
    leaf = path_parts[-1]
    pattern = re.compile(r"^(\s*)" + re.escape(leaf) + r":.*$")

    for index in range(start, end):
        match = pattern.match(lines[index])
        if match and len(match.group(1)) > parent_indent:
            lines[index] = f"{match.group(1)}{leaf}: {value}"
            return True

    if required:
        raise SystemExit("Key not found: " + ".".join(path_parts))
    return False

set_existing(["settings", "internal-webserver", "enabled"], "true")
set_existing(["settings", "internal-webserver", "bind"], "0.0.0.0")
set_existing(["settings", "internal-webserver", "port"], str(port))
set_existing(["settings", "ui", "coordinates", "enabled"], "true", required=False)
set_existing(["settings", "ui", "sidebar", "pinned"], "unpinned", required=False)

if public_url:
    escaped = public_url.replace("'", "''")
    set_existing(["settings", "web-address"], f"'{escaped}'", required=False)

# Keep settings.web-directory.path exactly as generated by squaremap.
# On Fabric this is usually "web", resolved relative to the squaremap/ directory.
path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("CONFIG_UPDATED")
PY

INFO="$(
  docker exec -i "$CONTAINER" python3 - "$CONFIG" <<'PY'
from __future__ import annotations

import re
import sys
from pathlib import Path

config = Path(sys.argv[1])
lines = config.read_text(encoding="utf-8").splitlines()

def indent(line: str) -> int:
    return len(line) - len(line.lstrip(" "))

def nested_value(keys: list[str], default: str = "") -> str:
    start, end, parent_indent = 0, len(lines), -1

    for key in keys[:-1]:
        pattern = re.compile(r"^(\s*)" + re.escape(key) + r":\s*(?:#.*)?$")
        found = None
        for i in range(start, end):
            match = pattern.match(lines[i])
            if match and len(match.group(1)) > parent_indent:
                found = (i, len(match.group(1)))
                break
        if found is None:
            return default
        pos, parent_indent = found
        start, end = pos + 1, len(lines)
        for j in range(start, len(lines)):
            stripped = lines[j].strip()
            if stripped and not stripped.startswith("#") and indent(lines[j]) <= parent_indent:
                end = j
                break

    leaf = keys[-1]
    pattern = re.compile(r"^(\s*)" + re.escape(leaf) + r":\s*(.*?)\s*(?:#.*)?$")
    for i in range(start, end):
        match = pattern.match(lines[i])
        if match and len(match.group(1)) > parent_indent:
            return match.group(2).strip().strip("'\"")
    return default

web_path = nested_value(["settings", "web-directory", "path"], "web")
webroot = Path(web_path)
if not webroot.is_absolute():
    webroot = config.parent / webroot

print(str(config))
print(str(webroot))
PY
)"

CONFIG_RESOLVED="$(printf '%s\n' "$INFO" | sed -n '1p')"
WEBROOT="$(printf '%s\n' "$INFO" | sed -n '2p')"

echo
echo "[OK] Configuration updated"
echo "Config  : $CONFIG_RESOLVED"
echo "Webroot : $WEBROOT"
echo "Escucha : 0.0.0.0:$PORT"
[[ -n "$PUBLIC_URL" ]] && echo "URL     : $PUBLIC_URL"
echo
echo "Restart the Minecraft server to apply the port."
